stages:
  - lint
  - analyze
  - build
  - coverage
  - sanitizers
  - release

variables:
  CLANG_FORMAT_VERSION: "21"
  CC: clang
  CXX: clang++

default:
  image: ubuntu:22.04
  before_script:
    - apt-get update
    - apt-get install -y wget gnupg python3 python3-pip ninja-build clang clang-tidy clang-format-${CLANG_FORMAT_VERSION}
    - pip3 install --no-cache-dir meson gcovr

lint:
  stage: lint
  script:
    - files=$(find src include app tests -name '*.cpp' -o -name '*.hpp')
    - if [ -n "$files" ]; then clang-format-${CLANG_FORMAT_VERSION} --dry-run --Werror $files; fi

analyze:
  stage: analyze
  needs: ["lint"]
  script:
    - meson setup build-tidy --buildtype=debug
    - meson compile -C build-tidy
    - files=$(find src include app tests -name '*.cpp')
    - |
      for f in $files; do
        echo "==> clang-tidy $f"
        clang-tidy "$f" -p build-tidy --warnings-as-errors='*'
      done

build_debug:
  stage: build
  needs: ["analyze"]
  script:
    - meson setup build --buildtype=debug
    - meson compile -C build
    - meson test -C build --print-errorlogs

build_release:
  stage: build
  needs: ["analyze"]
  script:
    - meson setup build-release --buildtype=release
    - meson compile -C build-release
    - meson test -C build-release --print-errorlogs

coverage:
  stage: coverage
  needs: ["build_debug"]
  script:
    - meson setup build-coverage --buildtype=debug -Db_coverage=true
    - meson compile -C build-coverage
    - meson test -C build-coverage --print-errorlogs
    - gcovr -r . --xml-pretty -o coverage.xml --html-details coverage.html || true
  artifacts:
    when: always
    paths:
      - coverage.xml
      - coverage.html

asan:
  stage: sanitizers
  needs: ["build_debug"]
  script:
    - meson setup build-asan --buildtype=debug -Db_sanitize=address -Db_lundef=false
    - meson compile -C build-asan
    - meson test -C build-asan --print-errorlogs

ubsan:
  stage: sanitizers
  needs: ["build_debug"]
  script:
    - meson setup build-ubsan --buildtype=debug -Db_sanitize=undefined -Db_lundef=false
    - meson compile -C build-ubsan
    - meson test -C build-ubsan --print-errorlogs

tsan:
  stage: sanitizers
  needs: ["build_debug"]
  script:
    - meson setup build-tsan --buildtype=debug -Db_sanitize=thread -Db_lundef=false
    - meson compile -C build-tsan
    - meson test -C build-tsan --print-errorlogs

release:
  stage: release
  rules:
    - if: '$CI_COMMIT_TAG'
    - when: never
  script:
    - meson setup build-release --buildtype=release
    - meson compile -C build-release
    - meson test -C build-release --print-errorlogs
    - meson install -C build-release --destdir=install-root
    - tar czf awesome_calc-${CI_COMMIT_TAG}-linux.tar.gz -C install-root .
  artifacts:
    when: on_success
    paths:
      - awesome_calc-*-linux.tar.gz
