
name: 'Setup Meson C++ env'
description: 'Install Python, Meson, Ninja and configure cache'
inputs:
  python-version:
    description: 'Python version'
    required: false
    default: '3.12'

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Ensure cache directories
      shell: bash
      run: |
        mkdir -p ~/.cache/pip
        mkdir -p ~/.cache/meson

    - name: Cache pip & meson
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/pip
          ~/.cache/meson
        key: ${{ runner.os }}-pip-meson-${{ hashFiles('.github/actions/setup-meson-env/action.yml') }}
        restore-keys: |
          ${{ runner.os }}-pip-meson-

    - name: Install Meson + Ninja
      run: |
        python -m pip install --upgrade pip
        python -m pip install meson ninja
      shell: bash

    - name: Ensure GoogleTest wrap
      shell: bash
      run: |
        set -euo pipefail
        mkdir -p subprojects
        if [ ! -f subprojects/gtest.wrap ]; then
          meson wrap install gtest
        fi
